// @ts-check
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import robotsTxt from 'astro-robots-txt';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import node from '@astrojs/node';
import visualManifest from './src/data/visuals-manifest.json';

const siteUrl = 'https://redreamality.com';
/** @type {Record<string, string>} */
const visualLanguagePrefixes = { en: '', zh: '/cn', ja: '/ja' };
/** @type {string[]} */
const visualSitemapPages = [];
/** @type {Set<string>} */
const unavailableVisualPaths = new Set();

for (const work of visualManifest) {
  if (work.status !== 'published') continue;
  for (const [lang, localized] of Object.entries(work.locales)) {
    const prefix = visualLanguagePrefixes[lang];
    if (prefix === undefined) continue;
    const path = `${prefix}/visuals/${work.slug}/`;
    if ('artifact' in localized && localized.artifact) {
      visualSitemapPages.push(new URL(path, siteUrl).toString());
    } else {
      unavailableVisualPaths.add(path);
    }
  }
}

// https://astro.build/config
export default defineConfig({
  site: siteUrl,
  base: '/',
  trailingSlash: 'always',
  output: 'static',
  integrations: [
    tailwind({
      // 启用 JIT 模式
      applyBaseStyles: true,
    }),
    mdx({
      remarkPlugins: [remarkMath],
      rehypePlugins: [[rehypeKatex, {
        // KaTeX options
        strict: false,
        macros: {
          "\\bmatrix": "\\begin{bmatrix}#1\\end{bmatrix}",
          "\\pmatrix": "\\begin{pmatrix}#1\\end{pmatrix}",
          "\\vmatrix": "\\begin{vmatrix}#1\\end{vmatrix}",
          "\\Vmatrix": "\\begin{Vmatrix}#1\\end{Vmatrix}",
          "\\matrix": "\\begin{matrix}#1\\end{matrix}"
        }
      }]]
    }),
    sitemap({
      customPages: [
        'https://redreamality.com/benchmark-papers/',
        ...visualSitemapPages,
      ],
      filter: (page) => {
        // Exclude private pages
        if (page.includes('/private/')) return false;

        // Exclude 404 pages
        if (page.includes('/404')) return false;

        // Exclude admin pages
        if (page.includes('/admin')) return false;

        // Exclude test pages
        if (page.includes('/test-')) return false;

        // Parse URL to get pathname for precise matching
        const url = new URL(page);
        const path = url.pathname;

        // Exclude redirect pages - these have noindex meta tags
        // Redirect from /talks/* to /garden/talks/*
        if (path === '/talks/' || path === '/talks') return false;
        if (path.match(/^\/talks\/[^/]+\/?$/)) return false;
        if (path === '/cn/talks/' || path === '/cn/talks') return false;
        if (path.match(/^\/cn\/talks\/[^/]+\/?$/)) return false;
        if (path === '/ja/talks/' || path === '/ja/talks') return false;
        if (path.match(/^\/ja\/talks\/[^/]+\/?$/)) return false;

        // Redirect from /garden/blog/* to /blog/*
        if (path.includes('/garden/blog/')) return false;

        // Raw visual endpoints are generated by TypeScript routes, so available
        // artifacts are listed through customPages. Exclude missing locales and
        // legacy HTML Showcase redirects from the sitemap.
        if (unavailableVisualPaths.has(path)) return false;
        if (path.match(/^\/(?:cn\/|ja\/)?blog\/html\/agent-architecture-showcase\/?$/)) return false;

        return true;
      },
      changefreq: 'weekly',
      serialize: (item) => {
        const url = new URL(item.url);
        const path = url.pathname;
        return {
          ...item,
          priority: path === '/' ? 1.0 :
                   path.includes('/tags/') ? 0.3 :
                   0.8,
        };
      },
    }),
    robotsTxt({
      policy: [
        {
          userAgent: '*',
          allow: '/',
          disallow: ['/private', '/admin'],
          crawlDelay: 10,
        },
      ],
      sitemap: true,
    }),
  ],
  markdown: {
    shikiConfig: {
      theme: 'dracula',
      wrap: true
    },
    remarkPlugins: [remarkMath],
    rehypePlugins: [[rehypeKatex, {
      // KaTeX options
      strict: false,
      macros: {
        "\\bmatrix": "\\begin{bmatrix}#1\\end{bmatrix}",
        "\\pmatrix": "\\begin{pmatrix}#1\\end{pmatrix}",
        "\\vmatrix": "\\begin{vmatrix}#1\\end{vmatrix}",
        "\\Vmatrix": "\\begin{Vmatrix}#1\\end{Vmatrix}",
        "\\matrix": "\\begin{matrix}#1\\end{matrix}"
      }
    }]]
  }
});
